version: '3.8'

services:
  api:
    build: .
    container_name: radiology_api
    restart: always
    command: sh docker-entrypoint.sh node server.js
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/radiology
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
      - JWT_SECRET=supersecretkey
      - EMAIL_FROM=no-reply@example.com
      - SMTP_HOST=smtp.example.com
      - SMTP_PORT=587
      - SMTP_USER=your_user
      - SMTP_PASS=your_pass
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: radiology_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: radiology
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: radiology_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api

volumes:
  postgres_data:
